import type { Metadata } from "next";
import "./globals.css";
// import { Provider } from "react-redux";
// import { store } from "@/app/store/index";

import {Footer} from "./commoncomponents/Footer";
import { Navbar } from "./commoncomponents/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/fav2.ico",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        {/* <Provider store={store}> */}
          <Navbar />
          <main>{children}</main>
          <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
